name: Update

on:
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install requests

    - name: Read
      run: |
        cp ${{ github.workspace }}/run.py ${{ github.workspace }}/updater.py
        echo "${{ secrets.KEY }}" > api.txt
        sed -i '183 r api.txt' ${{ github.workspace }}/updater.py
        python ${{ github.workspace }}/updater.py
